server:
  port: 8082

spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: <your_client_id>
            client-secret: <your_client_secret>
            authorization-grant-type: client_credentials
        provider:
          cognito:
            token-uri: <your_pool_domain>/oauth2/token

user-schedule-service:
  get-schedule:
    url: http://localhost:8081/user-schedule/schedule
  update-schedule:
    url: http://localhost:8081/user-schedule/schedule/{id}
